/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "MathTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MathTest__factory>;
    getContractFactory(
      name: "TokenTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TokenTest__factory>;
    getContractFactory(
      name: "UdexLibraryTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UdexLibraryTest__factory>;
    getContractFactory(
      name: "UdexERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UdexERC20__factory>;
    getContractFactory(
      name: "UdexFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UdexFactory__factory>;
    getContractFactory(
      name: "UdexPool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UdexPool__factory>;
    getContractFactory(
      name: "UdexRouter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UdexRouter__factory>;

    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "MathTest",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MathTest>;
    getContractAt(
      name: "TokenTest",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TokenTest>;
    getContractAt(
      name: "UdexLibraryTest",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UdexLibraryTest>;
    getContractAt(
      name: "UdexERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UdexERC20>;
    getContractAt(
      name: "UdexFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UdexFactory>;
    getContractAt(
      name: "UdexPool",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UdexPool>;
    getContractAt(
      name: "UdexRouter",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UdexRouter>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
