/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MathTest } from "./MathTest";
export type { TokenTest } from "./TokenTest";
export type { UdexLibraryTest } from "./UdexLibraryTest";
